### ISSUE TITLE
More settings for Areacopy?

### ISSUE THREAD

**Issue by andrewpros** [brussell1/Shaders#2]
Hi.

The AreaCopy fx is great, i was looking for something like that for a while.

Is it possible to add more options to it, like customizable opacity and scale (resize)? That would make it perfect.

**Comment by brussell1** [comment]
Sure. I'll look into it.

**Comment by andrewpros** [comment]
Thx.

**Comment by brussell1** [comment]
I've updated the shader. See commit https://github.com/brussell1/Shaders/commit/1800c3ee5dfe68f52c8909ffef724c9f0365440a for details.

I let this issue stay open for some future requests.

**Comment by andrewpros** [comment]
This is amazing, thank u.

**Comment by Mr-Foxtrot** [comment]
Could there be an option to rotate the copied area? I love this shader and would find it very helpful for an option to rotate the copied area independently of the source.

**Comment by Mr-Foxtrot** [comment]
is this shader still being worked on?

**Comment by brussell1** [comment]
Yes. Can you describe your use case a bit or why a rotation would be useful?

**Comment by Mr-Foxtrot** [comment]
> Yes. Can you describe your use case a bit or why a rotation would be useful?

Well, personally for me I find a option to rotate the copied area useful for some games that don't offer a lot of customization in regards to their GUI/HUD. It can also apply to some other games with elements that you can crop and flip or rotate for a bit of extra customization. An example being FNF, as it's arrow layouts support up/down scroll and that's all the customization available. No way to configure it to be horizontal at all unless you modify the game directly. Sure, some visuals would look a little wonky but otherwise still function fine.

This shader, while very niche, could be incredibly handy for tweaking the UI of some games to face a different rotation/position than what is normally possible.

I'd be very thankful, and appreciate implementation of such an option.

**Comment by brussell1** [comment]
I've updated the shader. See commit https://github.com/brussell1/Shaders/commit/4b95c3ae444326df6cf2a7a4265083915c3647ec for details.

**Comment by Mr-Foxtrot** [comment]
It works perfectly, thank you!!!
